# 语言
language: java
jdk:
  - openjdk8

sudo: false

before_install:
  - chmod +x ./mvnw

# 执行脚本
script: 
  - git clone https://github.com/hbstarjason/springboot-k8s-example
  - cd springboot-k8s-example
  - mvn test
  - mvn clean package -Dmaven.test.skip=true"
  
  
# 通知
notifications:
  email:
    recipients:
      - 305201518@qq.com
    on_success: always # default: change
    on_failure: always # default: always
# 缓存
cache:
  directories:
    - '$HOME/.m2/repository'
