# 语言
language: java
jdk:
  - openjdk8

before_install:
 - chmod +x ./mvnw

# 执行脚本
script: "mvn clean package -Dmaven.test.skip=true -s ./settings.xml"
# 通知
notifications:
  email:
    recipients:
      - 305201518@qq.com
    on_success: always # default: change
    on_failure: always # default: always
# 缓存
cache:
  directories:
    - '$HOME/.m2/repository'
